In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
a = (1,2,3)

In [9]:
a

(1, 2, 3)

In [1]:
import numpy as np

In [11]:
np.array(a)

array([1, 2, 3])

In [12]:
l=[1,2,3]

In [13]:
np.array(l)

array([1, 2, 3])

In [14]:
np.array([1,2,3])

array([1, 2, 3])

In [15]:
# 0-D Array

a = np.array(46)
a

array(46)

In [16]:
a.ndim

0

In [17]:
# 1-D Array

b = np.array([46])
b

array([46])

In [18]:
b.ndim

1

In [19]:
# 4-D Array
c = np.array([[[[46]]]])
c

array([[[[46]]]])

In [20]:
c.ndim

4

In [21]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
c = a.reshape(2,2,2)
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a = np.zeros([3,4], dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
for i in range(a.shape[0]): #rows
    for j in range(a.shape[1]): #columns
        a[i,j] = (i+1)*(j+1)
print(a)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]


In [ ]:
a.shape

(3, 4)

In [ ]:
a = [1,2,3] #list
print(a)

[1, 2, 3]


In [ ]:
import numpy as np

In [ ]:
b = np.array([1,2,3]) #array
print(b)

[1 2 3]


In [ ]:
b = np.array([[1,2,3]])
print(b)

[[1 2 3]]


In [ ]:
l1 = [1,2,3]
l2 = [2,3,4]
l3 = [3,4,5]
l = np.array([l1,l2,l3])
l

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [1]:
import numpy as np
c = np.array(range(5))
print(c)

[0 1 2 3 4]


In [ ]:
d = np.array(range(2,11,2))
print(d)

[ 2  4  6  8 10]


In [ ]:
arange = np.arange(5)
print(arange)

[0 1 2 3 4]


In [ ]:
arrange = np.arange(2,16,2)
print(arrange)

[ 2  4  6  8 10 12 14]


In [ ]:
x = np.array([[1,2],[5,6]])
print(x)

[[1 2]
 [5 6]]


In [ ]:
y = np.array([[5,6],[9,0]])
print(y)

[[5 6]
 [9 0]]


In [ ]:
print(x+y)

[[ 6  8]
 [14  6]]


In [ ]:
print(np.add(x,y))

[[ 6  8]
 [14  6]]


In [ ]:
print(np.subtract(x,y))

[[-4 -4]
 [-4  6]]


In [ ]:
print(np.multiply(x,y))

[[ 5 12]
 [45  0]]


In [ ]:
print(np.dot(x,y))

[[23  6]
 [79 30]]


In [ ]:
x.dot(y)

array([[23,  6],
       [79, 30]])

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [ ]:
print(np.cross(v1,v2))

[-3  6 -3]


In [ ]:
x = np.array([[1,2],[5,6]])
print(x)

[[1 2]
 [5 6]]


In [ ]:
y = np.array([[5,6],[9,0]])
print(y)
print(y.dtype)

[[5 6]
 [9 0]]
int64


In [ ]:
print(np.sum(x,axis=0))

[6 8]


In [ ]:
print(np.sum(x,axis=1))

[ 3 11]


In [ ]:
a = np.array([True,False])
print(a)
print(a.dtype)

[ True False]
bool


In [ ]:
f = np.array([[5.0,6.0],[9.0,0.0]])
print(f.dtype)

float64


In [ ]:
print(np.array(['2006-10-10']))

['2006-10-10']


In [ ]:
a = np.array(['2006-10-10'],dtype='M8[D]')
a.dtype

dtype('<M8[D]')

In [ ]:
str = np.array(['A','BB','CCCC'])
str.dtype

dtype('<U4')

In [ ]:
#Type Converison
intg = np.array(['1,2,3'])
intg

array(['1,2,3'], dtype='<U5')

In [ ]:
intj = np.array(['1','2','33'])
intj

array(['1', '2', '33'], dtype='<U2')

In [ ]:
intj = intj.astype('i')
intj

array([ 1,  2, 33], dtype=int32)

In [ ]:
intj = intj.astype('f')
intj

array([ 1.,  2., 33.], dtype=float32)

In [ ]:
str = str.astype('S4')
str

array([b'A', b'BB', b'CCCC'], dtype='|S4')

In [ ]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.sum(arr1), np.mean(arr1), np.min(arr1), np.max(arr1)  #Aggregate functions

(np.int64(21), np.float64(3.5), np.int64(1), np.int64(6))

In [ ]:
mat = np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.sum(mat,axis=0)

array([5, 7, 9])

In [ ]:
np.sum(mat,axis=1)

array([ 6, 15])

In [ ]:
np.prod(mat,axis=0)

array([ 4, 10, 18])

In [ ]:
np.prod(mat,axis=1)

array([  6, 120])

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[3]) 
print(arr[-2]) #negative indexing

4
4


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[0][1] , arr2[1][1] )

2 5


In [ ]:
arr3 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3[1][0][2])
arr3

9


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr4 = np.array([20,25,30,35,40,45,50])
arr4[1:6]

array([25, 30, 35, 40, 45])

In [ ]:
arr5 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
arr5[1:7:2]

array([[ 7,  8,  9, 10, 11, 12]])

In [24]:
arr6 = np.array([1,2,3,4,5,6,7,8,9,10])
arr6.ndim
arr6.shape


(10,)

In [27]:
arr6.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
arr7=np.array([1,2,3,4,5,6,7,8])
arr7.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
arr8=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a = arr8.reshape(2,2,2,2)
arr8.reshape(-1) #Flating of the array
print(a.shape)


(2, 2, 2, 2)


In [18]:
ar = np.array([1,2,3,4,5])
for i in range(len(ar)):
    print(ar[i])

1
2
3
4
5


In [27]:
ar2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a1 = ar2.reshape(3,4)
# print(a1)
for i in range(len(a1)):
    for j in range(1,len(a1)-1):
        print(a1[i])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [37]:
ar3 = np.array([1,2,3])
ar4 = np.array([3,4,5])
con = np.concatenate((ar3,ar4))
print(con)

[1 2 3 3 4 5]


In [49]:
n1 = np.array([1,2,3,4])
n2 = np.array(['a','b','c','d'])
# np.stack([n1,n2])
np.vstack([n1,n2]) # vertical stack array
np.hstack([n1,n2]) # horizontal stack array
np.column_stack([n1,n2]) # column stack array 
np.dstack([n1,n2]) # depth stack array

array([[['1', 'a'],
        ['2', 'b'],
        ['3', 'c'],
        ['4', 'd']]], dtype='<U21')

In [3]:
arrr = np.array([23,45,43,65,34,26])
np.sort(arrr)

array([23, 26, 34, 43, 45, 65])

In [4]:
arrr2 = np.array(['raj','arum','prya','soumya','tuhin'])
np.sort(arrr2)

array(['arum', 'prya', 'raj', 'soumya', 'tuhin'], dtype='<U6')

In [9]:
data =  np.array([12,13,24,25,26])
np.where(data==13)

(array([1]),)