In [1]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 17.2 MB/s  0:00:003.8 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [ ]:
a = (1,2,3)

In [ ]:
a

In [2]:
import numpy as np

In [10]:
np.array(a)

array([1, 2, 3])

In [11]:
l=[1,2,3]

In [12]:
np.array(l)

array([1, 2, 3])

In [13]:
np.array([1,2,3])

array([1, 2, 3])

In [14]:
# 0-D Array

a = np.array(46)
a

array(46)

In [15]:
a.ndim

0

In [16]:
# 1-D Array

b = np.array([46])
b

array([46])

In [17]:
b.ndim

1

In [18]:
# 4-D Array
c = np.array([[[[46]]]])
c

array([[[[46]]]])

In [19]:
c.ndim

4

In [20]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
b = a.reshape(3,3)
b

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
c = a.reshape(2,2,2)
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a = np.zeros([3,4], dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
for i in range(a.shape[0]): #rows
    for j in range(a.shape[1]): #columns
        a[i,j] = (i+1)*(j+1)
print(a)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]


In [ ]:
a.shape

(3, 4)

In [ ]:
a = [1,2,3] #list
print(a)

[1, 2, 3]


In [ ]:
import numpy as np

In [ ]:
b = np.array([1,2,3]) #array
print(b)

[1 2 3]


In [ ]:
b = np.array([[1,2,3]])
print(b)

[[1 2 3]]


In [ ]:
l1 = [1,2,3]
l2 = [2,3,4]
l3 = [3,4,5]
l = np.array([l1,l2,l3])
l

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
import numpy as np
c = np.array(range(5))
print(c)

[0 1 2 3 4]


In [ ]:
d = np.array(range(2,11,2))
print(d)

[ 2  4  6  8 10]


In [ ]:
arange = np.arange(5)
print(arange)

[0 1 2 3 4]


In [ ]:
arrange = np.arange(2,16,2)
print(arrange)

[ 2  4  6  8 10 12 14]


In [24]:
x = np.array([[1,2],[5,6]])
print(x)

[[1 2]
 [5 6]]


In [25]:
y = np.array([[5,6],[9,0]])
print(y)

[[5 6]
 [9 0]]


In [ ]:
print(x+y)

[[ 6  8]
 [14  6]]


In [ ]:
print(np.add(x,y))

[[ 6  8]
 [14  6]]


In [26]:
print(np.subtract(x,y))

[[-4 -4]
 [-4  6]]


In [27]:
print(np.multiply(x,y))

[[ 5 12]
 [45  0]]


In [28]:
print(np.dot(x,y))

[[23  6]
 [79 30]]


In [ ]:
x.dot(y)

array([[23,  6],
       [79, 30]])

In [29]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [30]:
print(np.cross(v1,v2))

[-3  6 -3]


In [33]:
x = np.array([[1,2],[5,6]])
print(x)

[[1 2]
 [5 6]]


In [42]:
y = np.array([[5,6],[9,0]])
print(y)
print(y.dtype)

[[5 6]
 [9 0]]
int64


In [36]:
print(np.sum(x,axis=0))

[6 8]


In [37]:
print(np.sum(x,axis=1))

[ 3 11]


In [40]:
a = np.array([True,False])
print(a)
print(a.dtype)

[ True False]
bool


In [44]:
f = np.array([[5.0,6.0],[9.0,0.0]])
print(f.dtype)

float64


In [46]:
print(np.array(['2006-10-10']))

['2006-10-10']


In [47]:
a = np.array(['2006-10-10'],dtype='M8[D]')
a.dtype

dtype('<M8[D]')

In [51]:
str = np.array(['A','BB','CCCC'])
str.dtype

dtype('<U4')

In [58]:
#Type Converison
intg = np.array(['1,2,3'])
intg

array(['1,2,3'], dtype='<U5')

In [6]:
intj = np.array(['1','2','33'])
intj

array(['1', '2', '33'], dtype='<U2')

In [7]:
intj = intj.astype('i')
intj

array([ 1,  2, 33], dtype=int32)

In [67]:
intj = intj.astype('f')
intj

array([ 1.,  2., 33.], dtype=float32)

In [68]:
str = str.astype('S4')
str

array([b'A', b'BB', b'CCCC'], dtype='|S4')

In [4]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.sum(arr1), np.mean(arr1), np.min(arr1), np.max(arr1)  #Aggregate functions

(np.int64(21), np.float64(3.5), np.int64(1), np.int64(6))

In [3]:
mat = np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.sum(mat,axis=0)

array([5, 7, 9])

In [5]:
np.sum(mat,axis=1)

array([ 6, 15])

In [6]:
np.prod(mat,axis=0)

array([ 4, 10, 18])

In [7]:
np.prod(mat,axis=1)

array([  6, 120])

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[3]) 
print(arr[-2]) #negative indexing

4
4


In [18]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[0][1] , arr2[1][1] )

2 5
